### ISSUE TITLE
Mistral *La plateforme API*

### ISSUE THREAD

**Issue by tobozo** [arananet/hermes-ai-mistral#1]
hi,

In the readme there are several occurences of mispelled `Mistral Le plataforme API`, unless the typo is intentional it should read `Mistral La plateforme API`

I don't have outlook but I wonder if hermes-ai-mistral would be able to fix that :stuck_out_tongue_winking_eye:

**Comment by arananet** [comment]
Haha, who certifies the certifying entity that certified the certificate? ;)

Many thanks for the tip @tobozo
